const link1 = document.getElementById("link1")
const link2 = document.getElementById("link2")
const link3 = document.getElementById("link3")
const link4 = document.getElementById("link4")
const perso = document.getElementById("personagem")
let fases = 0
link1.addEventListener("click", ()=> {perso.style.animation = "fase1 4s ease forwards"; fases++})
// link1.addEventListener("click", () => {window.open("index.html", "_blank"); })
perso.addEventListener("animationend",()=> {window.open("index.html", "_blank")})
link1.addEventListener("click", ()=> perso.classList.remove("animacao_fase1"))
link2.addEventListener("click", ()=> window.open("index.html", "_blank"))
link3.addEventListener("click", ()=> window.open("index.html", "_blank"))
link4.addEventListener("click", ()=> window.open("index.html", "_blank"))
// const nome = localStorage.getItem('armazem')
// document.getElementById('is').innerText = nome
console.log(fases)